server:
  port: 9000

kakao:
  api:
    base-url: "https://kapi.kakao.com"
  oauth:
    base-url: "https://kauth.kakao.com"
    client-id: "47aa41577e358c5ba9d42460a82c1046"
    redirect-uri: "http://localhost:9000/oauth/kakao/redirect"

jwt:
  secret: "c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK"
  token-validity-in-seconds: 3600000


spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: "create"
  datasource:
    url: "jdbc:mysql://localhost:3306/everyoneparty"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: "root"
    password: "Rnjs@1q2w3e"

logging:
  level:
    org:
      springframework: INFO